INSERT INTO CLIENTE (ID, CPF, EMAIL, NOME) VALUES (1, '123.456.789-10', 'douglas.oliveira@app.com', 'DOUGLAS OLIVEIRA');
INSERT INTO CLIENTE (ID, CPF, EMAIL, NOME) VALUES (2, '321.654.987-01', 'maria.oliveira@app.com', 'MARIA OLIVEIRA');
INSERT INTO CLIENTE (ID, CPF, EMAIL, NOME) VALUES (3, '345.153.863-33', 'beatriz.oliveira@app.com', 'BEATRIZ OLIVEIRA');
COMMIT;